version: "0.1"
addresses:
  address@mailscript.com:
    keys:
      - name: owner
        read: true
        write: true
accessories:
  - name: sms to me
    type: sms
    sms: "+123456789"
  - name: address@mailscript.com
    type: mailscript-email
    address: address@mailscript.com
    key: owner
workflows:
  - name: Alerts to sms
    trigger:
      accessory: address@mailscript.com
      config:
        times:
          thisManySeconds: 60
          thisManyTimes: 2
        criterias:
          - subjectContains: alert
    actions:
      - accessory: sms to me
        config:
          type: sms
          text: Two alerts arrived within 60 seconds
